#:kivy 2.3.1

<ClickerSettings@Section>:

    height: '105dp'

    text: 'Clicker Settings'
    
    TriggerInput:
        current_trigger: "f7"
    NumberInput


<HolderSettings@Section>:

    height: '58dp'

    text: 'Holder Settings'
    
    TriggerInput:
        current_trigger: "f8"


<TopLayout>:
    
    font_size: '20dp'
    label_size: '40dp'
    spacing: '9dp'
    inner_spacing: '15dp'
    text: 'Vadim Clicker'
    
    ClickerSettings
    HolderSettings
