#:kivy 2.3.1
<Input>:

    # shared styles
    size_hint: (1, None)
    size: 0, '40dp'
    background_normal: ''
    background_down: ''
    background_color: 0, 0, 0, 0
    font_size: '20dp'
    color: 0, 63/255, 98/255, 1
    border_width: '1dp'

    # state-depedent styles
    bg_color_idle: rgba('#000005')
    bg_color_hover: rgba('#050516')
    bg_color_active: self.bg_color_idle
    
    border_color_idle: rgba('#151527')
    border_color_hover: rgba('#1B2A41')
    border_color_active: rgba('#004FB2')
    
    # default styles
    bg_color: self.bg_color_idle
    border_color: self.border_color_idle
    
    canvas.before:
        Color:
            rgba: self.bg_color
        RoundedRectangle:
            radius: [5,5,5,5]
            pos: self.pos
            size: self.size
        Color:
            rgba: self.border_color
        Line:
            width: self.border_width
            rounded_rectangle: [self.x+self.border_width, self.y+self.border_width, self.width-self.border_width*2, self.height-self.border_width*2, 5]
    

<NumberInput>:
    # TextInput's text color is always the last Color used in canvas.before
    # The following was added to prevent it from following border color.
    # But I liked how it changes color, so I disabled the fix.
    # Maybe temporarily.
    #canvas.before:
    #    Color:
    #        rgba: 0, 63/255, 98/255, 1


<Header>:
    pos: root.pos
    size_hint_y: None
    size: root.width, self.font_size
    font_size: '20dp'
    text_size: self.width, self.font_size
    halign: "left"
    valigh: "middle"
    color: 0, 85/255, 131/255, 1
    background_color: 0, 0, 0, 0


<Section>:
    font_size: '12dp'
    label_height: '16dp'
    spacing: '2dp'
    inner_spacing: '7dp'
    size_hint: 1, None
    
    Header:    
        text: root.text
        #height: root.label_height
        font_size: root.font_size
    
    StackLayout:
        size_hint: 1, None
        id: layout
        spacing: root.inner_spacing



<ClickerSettings@Section>:

    height: '105dp'

    text: 'Clicker Settings'
    
    TriggerInput:
        current_trigger: "f7"
    NumberInput


<HolderSettings@Section>:

    height: '58dp'

    text: 'Holder Settings'
    
    TriggerInput:
        current_trigger: "f8"


<TopLayout>:
    
    font_size: '20dp'
    label_size: '40dp'
    spacing: '9dp'
    inner_spacing: '15dp'
    text: 'Vadim Clicker'
    
    ClickerSettings
    HolderSettings
    


<Background>:
    line_gap: '7dp'
    line_width: '1dp'

    canvas:
        Color:
            rgba: (0,0,5/255,1)
        Rectangle:
            size: root.size
        Color:
            rgba: (15/255,21/255,39/255,1)
        Line:
            points: (self.line_gap, 0, self.line_gap, root.height)
            width: self.line_width
        Line:
            points: (root.width-self.line_gap, 0, root.width-self.line_gap, root.height)
            width: self.line_width
        Line:
            points: (0, self.line_gap, root.width, self.line_gap)
            width: self.line_width
        Line:
            points: (0, root.height-self.line_gap, root.width, root.height-self.line_gap)
            width: self.line_width
<RootWidget>:
    size: '250dp', '229dp'
    padding: '14dp'

    Background:
        size: root.size
    TopLayout
        size: (root.width-root.padding*2, root.height-root.padding*2)
        pos: (root.padding, root.padding)
